//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int mid { get; set; }
        public int subid { get; set; }
        public int classid { get; set; }
        public int examid { get; set; }
        public int submarks { get; set; }
        public Nullable<bool> isprasent { get; set; }
        public string Mstatus { get; set; }
        public int Admissionum { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual exam exam { get; set; }
        public virtual student student { get; set; }
        public virtual subjectt subjectt { get; set; }
    }
}
