//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class schoolEntities3 : DbContext
    {
        public schoolEntities3()
            : base("name=schoolEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<exam> exams { get; set; }
        public virtual DbSet<Exammapping> Exammappings { get; set; }
        public virtual DbSet<feemapping> feemappings { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<subjectmapping> subjectmappings { get; set; }
        public virtual DbSet<subjectt> subjectts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
